### ISSUE TITLE
Catkin_make failed.

### ISSUE THREAD

**Issue by qwertyuiop789456** [epfl-lasa/iiwa_ros#109]
**I have added all the packages as per instruction. But when i do catkin_make i get the following error in the terminal at 98 percent.**
I have attached an google doc as the error goes up to 33 pages. I have attached a snapshot of first and end of the error.

https://docs.google.com/document/d/1M8b-NZ5g3CUhBh0zA0FNuWTBxQiMYdSvkMQtOSvqqbo/edit?usp=sharing

![Screenshot from 2023-07-14 18-39-29](https://github.com/epfl-lasa/iiwa_ros/assets/57223755/69ef2163-c176-4bc7-86ee-5010188db25f)

![Screenshot from 2023-07-14 18-39-40](https://github.com/epfl-lasa/iiwa_ros/assets/57223755/bbc118c9-9f36-421d-8dba-a4720ef2d803)

**Comment by costashatz** [comment]
@qwertyuiop789456 thanks for using the library.

Which ROS version are you using? And which Gazebo version? How did you install Gazebo?

From the message, the error should be fixed if you change [this line](https://github.com/epfl-lasa/iiwa_ros/blob/master/iiwa_gazebo/CMakeLists.txt#L51) to (C++14 or above):

```CMake
set_property(TARGET iiwa_gazebo_gravity_compensation_hw_sim PROPERTY CXX_STANDARD 14)
```

But I am speculating :)

**Comment by qwertyuiop789456** [comment]
Hi @costashatz . sorry for not mentioning the details. 

ROS - Noetic
Gazebo - 11.11.0

Gazebo was installed when i used "sudo apt install ros-noetic-desktop-full"

Even after changing to 14, still the error remains.

![Screenshot from 2023-07-17 09-58-24](https://github.com/epfl-lasa/iiwa_ros/assets/57223755/d599068a-4de3-4881-afb0-bb591d859cef)

**Comment by costashatz** [comment]
> ROS - Noetic
> Gazebo - 11.11.0

This is the issue. Gazebo and ROS in general changed to using the `std` lib instead of `boost` at `Noetic`. At the moment, the recommended version (as said in the docs) is to use `Melodic` or `Kinetic`. The package has been extensively used and tested in those versions.

Let me put a TO-DO to make the package compatible with `Noetic` as well. Please switch to `Melodic` until I make it compatible with `Noetic`.

Closing this issue.
